export const billTags = [
    {
        id: 1,
        name: '午餐',
        clicked: false,
        color: 'green',
        icon: 'chat-o',
    },
    {
        id: 2,
        name: '晚餐',
        clicked: false,
        color: 'blue',
        icon: 'chat-o',
    },
    {
        id: 3,
        name: '宵夜',
        clicked: false,
        color: 'yellow',
        icon: 'fire-o',
    },
    {
        id: 4,
        name: '外卖',
        clicked: false,
        color: 'purple',
        icon: 'chat-o',
    },
    {
        id: 5,
        name: '出行',
        clicked: false,
        color: 'red',
        icon: 'fire-o',
    },
    {
        id: 1,
        name: '午餐',
        clicked: false,
        color: 'green',
        icon: 'chat-o',
    },
    {
        id: 2,
        name: '晚餐',
        clicked: false,
        color: 'blue',
        icon: 'chat-o',
    },
    {
        id: 3,
        name: '宵夜',
        clicked: false,
        color: 'yellow',
        icon: 'fire-o',
    },
    {
        id: 4,
        name: '外卖',
        clicked: false,
        color: 'purple',
        icon: 'chat-o',
    },
    {
        id: 5,
        name: '出行',
        clicked: false,
        color: 'red',
        icon: 'fire-o',
    },
    {
        id: 1,
        name: '午餐',
        clicked: false,
        color: 'green',
        icon: 'chat-o',
    },
    {
        id: 2,
        name: '晚餐',
        clicked: false,
        color: 'blue',
        icon: 'chat-o',
    },
    {
        id: 3,
        name: '宵夜',
        clicked: false,
        color: 'yellow',
        icon: 'fire-o',
    },
    {
        id: 4,
        name: '外卖',
        clicked: false,
        color: 'purple',
        icon: 'chat-o',
    },
    {
        id: 5,
        name: '出行',
        clicked: false,
        color: 'red',
        icon: 'fire-o',
    },
    {
        id: 1,
        name: '午餐',
        clicked: false,
        color: 'green',
        icon: 'chat-o',
    },
    {
        id: 2,
        name: '晚餐',
        clicked: false,
        color: 'blue',
        icon: 'chat-o',
    },
    {
        id: 3,
        name: '宵夜',
        clicked: false,
        color: 'yellow',
        icon: 'fire-o',
    },
    {
        id: 4,
        name: '外卖',
        clicked: false,
        color: 'purple',
        icon: 'chat-o',
    },
    {
        id: 5,
        name: '出行',
        clicked: false,
        color: 'red',
        icon: 'fire-o',
    },
    {
        id: 3,
        name: '宵夜',
        clicked: false,
        color: 'yellow',
        icon: 'fire-o',
    },
    {
        id: 4,
        name: '外卖',
        clicked: false,
        color: 'purple',
        icon: 'chat-o',
    },
    {
        id: 5,
        name: '出行',
        clicked: false,
        color: 'red',
        icon: 'fire-o',
    },
    {
        id: 5,
        name: '出行',
        clicked: false,
        color: 'red',
        icon: 'fire-o',
    },
]
